#!/usr/bin/env bash

PROJECT_ROOT=$(git rev-parse --show-toplevel)

main() {
    local env_files=($(find_all_dotenv_files))
    for env_file in "${env_files[@]}"; do
        generate_env_example "$env_file"
    done
}

generate_env_example () {
    local env_file="$1"
    sed '/;;.*$/!s/=\S*/=/' "$env_file" > "$env_file.example"
}

find_all_dotenv_files () {
    find "$PROJECT_ROOT" -type f -iname '*.env*' ! -iname '*.example'
}

main "$@"
